name: Build

on:
  push:
    branches:
      - develop

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build (Develop)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

